export const Command = {
	CommonPing:11000,
	CommonPong:10000,
	CommonLogin:11001,
	CommonLoginAck:10001,
	CommonLogout:11002,
	CommonLogoutAck:10002,
	CommonKickPlayer:11003,
	CommonKickPlayerAckL:10003,
	CommonAnnounce:11004,
	CommonAnnounceAck:10004,
	CommonBroadcast:11005,
	CommonBroadcastAck:10005,
	CommonMaintain:11006,
	CommonMaintainAck:10006,
	CommonPlayerInfo    : 11007,
 	CommonPlayerInfoAck : 10007,
    PlayerJoinLobby:11011,
	PlayerJoinRoom  : 11012,
	PlayerJoinLobbyAck : 10011,
	PlayerJoinRoomAck  : 10012,

	PlayerWaitToJoinTable : 11013,
	PlayerJoinTable       : 11014,
	PlayerLeaveTable      : 11015,
	PlayerSeatHandUp      : 11018,

	PlayerWaitToJoinTableAck : 10013,
	PlayerJoinTableAck       : 10014,
	PlayerLeaveTableAck      : 10015,
	PlayerSeatSit            : 10016,
	PlayerSeatHandUpCheck    : 10017,
	PlayerSeatHandUpAck      : 10018,
	PlayerSeatReady          : 10019,

	PlayerListRooms    : 11020,
	PlayerListRoomsAck : 10020,
	PlayerSeatCommitCards    :11022,
	PlayerSeatCommitCardsAck :10022,
	PlayerLeaveRoom    : 11021,
	PlayerLeaveRoomAck : 10021,

	TableCreate         : 90000,
	TableFlowHandup     : 90010,
	TableFlowInit       : 90020,
	TableFlowGameBegin  : 90030,
	TableFlowDecision   : 90040,
	TableFlowCompare    : 90050,
	TableFlowSettlement : 90070,
	TableFlowEnd        : 90080,
	TableFlowCancel     : 90090,


	GamePlayerInfo : 90001,
	TableFlowHandupPlayers : 90011,
	GameRoomRule  : 90022,
	GameTableRule : 90023,

	TableFlowGameRound  : 90031,
	TableFlowShuffle    : 90032,
	TableFlowRandomCard : 90033,
	TableFlowDeal       : 90034,
	TableFlowSeatCard   : 90035,
	TableFlowPatternRecommand : 90041,
	TableFlowChoosePattern    : 90042,
	TableFlowDecisionDone     : 90043,
	TableFlowShowPlayerCards : 90051,
	TableFlowShowFront       : 90052,
	TableFlowShowMiddle      : 90053,
	TableFlowShowBack        : 90054,
	TableFlowShowSpecial     : 90055,
	TableFlowShowGan         : 90056,
	TableFlowShowHomerun     : 90057,
	TableFlowCompareResult   : 90058,
	TableFlowShowWinLose         : 90071,
	TableFlowShowCards           : 90072,
	TableFlowSettlementEnd       : 90073,
	TableFlowNextRoundRemainTime : 90074,

}

export const CommandMap = {
    // ErrorMsg
    [Command.S2C_ErrorAck]: "S2C_ErrorAck", 
    // Base     
    [Command.S2C_MemberBalance]: "S2C_MemberBalance",

	[Command.CommonPing]:"CP_Ping",
	[Command.CommonPong]:"CP_Pong",
	[Command.CommonLogin]:"CP_Login",
	[Command.CommonLoginAck]:"CP_LoginAck",
	[Command.CommonLogout]:"CP_Logout",
	[Command.CommonLogoutAck]:"CP_LogoutAck",
	[Command.CommonKickPlayer]:"CP_KickPlayer",
	[Command.CommonKickPlayerAckL]:"CP_KickPlayerAck",
	[Command.CommonAnnounce]:"CP_Announce",
	[Command.CommonAnnounceAck]:"CP_AnnounceAck",
	[Command.CommonBroadcast]:"CP_Broadcast",
	[Command.CommonBroadcastAck]:"CP_BroadcastAck",
	[Command.CommonMaintain]:"CP_Haintain",
    [Command.CommonMaintainAck]:"CP_MaintainAck",
    
    [Command.PlayerJoinLobby]:"CP_PlayerJointLobby",
	[Command.PlayerJoinRoom]  : "CP_PlayerJoinRoom",

	[Command.PlayerJoinLobbyAck] : "CP_PlayerJoinLobbyAck",
	[Command.PlayerJoinRoomAck]  : "CP_JoinRoomAck",

	[Command.PlayerWaitToJoinTable] : "CP_PlayerWaitToJoinTable",
	[Command.PlayerJoinTable]       : "CP_PlayerJoinTable",
	[Command.PlayerLeaveTable]     : "CP_PlayerLeaveTable",
	[Command.PlayerSeatHandUp]     : "CP_PlayerSeatHandUp",
	[Command.PlayerSeatCommitCards] : "CP_PlayerSeatCommitCards",
	[Command.PlayerSeatCommitCardsAck]: "PlayerSeatCommitCardsAck",

	[Command.GamePlayerInfo] : "CP_GamePlayerInfo",

	[Command.PlayerWaitToJoinTableAck] : "CP_PlayerWaitToJoinTableAck",
	[Command.PlayerJoinTableAck]       : "CP_PlayerJoinTableAck",
	[Command.PlayerLeaveTableAck]     : "CP_PlayerLeaveTableAck",
	[Command.PlayerSeatSit]           : "CP_PlayerSeatSit",
	[Command.PlayerSeatHandUpCheck]   : "CP_PlayerSeatHandUpCheck",
	[Command.PlayerSeatHandUpAck]     : "CP_PlayerSeatHandUpAck",
	[Command.PlayerSeatReady]         : "CP_PlayerSeatReady",

	[Command.PlayerListRooms]   : "CP_PlayerListRooms",
	[Command.PlayerListRoomsAck] : "CP_PlayerListRoomsAck",
	[Command.CommonPlayerInfo] : "CP_CommonPlayerInfo",
	[Command.CommonPlayerInfoAck] : "CP_CommonPlayerInfoAck",
	


	[Command.PlayerLeaveRoom]    : "CP_PlayerLeaveRoom",
	[Command.PlayerLeaveRoomAck] : "CP_PlayerLeaveRoomAck",

	[Command.TableCreate ]        : "CP_TableCreate",
	[Command.TableFlowHandup]     : "CP_TableFlowHandup",
	[Command.TableFlowInit]       : "CP_TableFlowInit",
	[Command.TableFlowGameBegin]  : "CP_TableFlowGameBegin",
	[Command.TableFlowDecision]   : "CP_TableFlowDecision",
	[Command.TableFlowCompare]    : "CP_TableFlowCompare",
	[Command.TableFlowSettlement] : "CP_TableFlowSettlement",
	[Command.TableFlowEnd]        : "CP_TableFlowEnd",
	[Command.TableFlowCancel]     : "CP_TableFlowCancel",



	[Command.TableFlowHandupPlayers] : "CP_TableFlowHandupPlayers",
	[Command.GameRoomRule]  : "CP_GameRoomRule",
	[Command.GameTableRule] : "CP_GameTableRule",

	[Command.TableFlowGameRound]  : "CP_TableFlowGameRound",
	[Command.TableFlowShuffle]    : "CP_TableFlowShuffle",
	[Command.TableFlowRandomCard] : "CP_TableFlowRandomCard",
	[Command.TableFlowDeal]       : "CP_TableFlowDeal",
	[Command.TableFlowSeatCard]   : "CP_TableFlowSeatCard",
	[Command.TableFlowPatternRecommand] : "CP_TableFlowPatternRecommand",
	[Command.TableFlowChoosePattern]    : "CP_TableFlowChoosePattern",
	[Command.TableFlowDecisionDone]     : "CP_TableFlowDecisionDone",
	[Command.TableFlowShowPlayerCards] : "CP_TableFlowShowPlayerCards",
	[Command.TableFlowShowFront]       : "CP_TableFlowShowFront",
	[Command.TableFlowShowMiddle]      : "CP_TableFlowShowMiddle",
	[Command.TableFlowShowBack]        : "CP_TableFlowShowBack",
	[Command.TableFlowShowSpecial]     : "CP_TableFlowShowSpecial",
	[Command.TableFlowShowGan]         : "CP_TableFlowShowGan",
	[Command.TableFlowShowHomerun]     : "CP_TableFlowShowHomerun",
	[Command.TableFlowCompareResult]   : "CP_TableFlowCompareResult",
	[Command.TableFlowShowWinLose]         : "CP_TableFlowShowWinLose",
	[Command.TableFlowShowCards]           : "CP_TableFlowShowCards",
	[Command.TableFlowSettlementEnd]       : "CP_TableFlowSettlementEnd",
	[Command.TableFlowNextRoundRemainTime] : "CP_TableFlowNextRoundRemainTime",
}

export const PokerCard = {
	900:	"Joker1",
	901:	"Joker2",

	401:	"AceOfSpade",
	402:	"TwoOfSpade",
	403:	"ThreeOfSpade",
	404:	"FourOfSpade",
	405:	"FiveOfSpade",
	406:	"SixOfSpade",
	407:	"SevenOfSpade",
	408:	"EightOfSpade",
	409:	"NineOfSpade",
	410:	"TenOfSpade",
	411:	"JackOfSpade",
	412:	"QueenOfSpade",
	413:	"KingOfSpade",

	301:	"AceOfHeart",
	302:	"TwoOfHeart",
	303:	"ThreeOfHeart",
	304:	"FourOfHeart",
	305:	"FiveOfHeart",
	306:	"SixOfHeart",
	307:	"SevenOfHeart",
	308:	"EightOfHeart",
	309:	"NineOfHeart",
	310:	"TenOfHeart",
	311:	"JackOfHeart",
	312:	"QueenOfHeart",
	313:	"KingOfHeart",

	201:	"AceOfDiamond",
	202:	"TwoOfDiamond",
	203:	"ThreeOfDiamond",
	204:	"FourOfDiamond",
	205:	"FiveOfDiamond",
	206:	"SixOfDiamond",
	207:	"SevenOfDiamond",
	208:	"EightOfDiamond",
	209:	"NineOfDiamond",
	210:	"TenOfDiamond",
	211:	"JackOfDiamond",
	212:	"QueenOfDiamond",
	213:	"KingOfDiamond",

	101:	"AceOfClub",
	102:	"TwoOfClub",
	103:	"ThreeOfClub",
	104:	"FourOfClub",
	105:	"FiveOfClub",
	106:	"SixOfClub",
	107:	"SevenOfClub",
	108:	"EightOfClub",
	109:	"NineOfClub",
	110:	"TenOfClub",
	111:	"JackOfClub",
	112:	"QueenOfClub",
	113:	"KingOfClub",


}
export const CardPattern = {
[0]: "CARD_FAILED",
[1]: "CARD_RECOM_FAILED",
[2]: "散牌",
[3]: "假一對",
[4]: "正一對",
[5]: "假兩對",
[6]: "正兩對",
[7]: "假三條",
[8]: "正三條",
[9]: "假順子",
[10]: "正順子",
[11]: "假同花",
[12]: "正同花",
[13]: "假一對同花",
[14]: "正一對同花",
[15]: "假兩對同花",
[16]: "正兩對同花",
[17]: "假三條同花",
[18]: "正三條同花",
[19]: "假葫蘆",
[20]: "正葫蘆",
[21]: "假鐵支",
[22]: "正鐵支",
[23]: "假柳丁",
[24]: "正柳丁",
[25]: "假五梅",
[26]: "正五梅",

}